Enable subscription-manager yum plugins
Katello/katello-client-bootstrap pull request #112
Opened 2016-10-05 23:02 UTC by sideangleside

This PR ensures that the following yum plugins are enabled in subscription-manager prior running the register or migration routines. 

- the **product-id** plugin - ensures that new product certificates are placed in /etc/pki/product. Without this, systems won't get the product certs when products are installed from the various Red Hat repositories. 
- the **subscription-manager** plugin - ensures that subscription-manager works properly.

2016-10-07 16:16 UTC, evgeni requested changes

2016-10-07 16:16 UTC, evgeni commented on bootstrap.py
> +      with open('/etc/yum/pluginconf.d/product-id.conf','w') as configfile:
`with` is Python 2.5+ only. :cry:
can EL5 please die?

2016-10-07 16:16 UTC, evgeni commented on bootstrap.py
> +    configparser = SafeConfigParser()
`configparser` sounds so generic, why not `productidconfig`?

2016-10-07 16:16 UTC, evgeni commented on bootstrap.py
> +    configparser = SafeConfigParser()
`configparser` sounds so generic, why not `submanconfig`?

2016-10-07 16:16 UTC, evgeni commented on bootstrap.py
> +      with open('/etc/yum/pluginconf.d/product-id.conf','w') as configfile:
`configfile` sounds so generic, why not `submanfile`?
also: wrong file!

2016-10-07 16:16 UTC, evgeni commented on bootstrap.py
> +      with open('/etc/yum/pluginconf.d/product-id.conf','w') as configfile:
`configfile` sounds so generic, why not `productidfile`?

2016-10-07 18:37 UTC, evgeni approved these changes

2016-10-07 19:30 UTC, sideangleside commented
Added some updates in commit https://github.com/Katello/katello-client-bootstrap/pull/112/commits/334cfba45035863863602bdc15f3b7c7aa495338 based on feedback

2016-10-07 19:32 UTC, evgeni commented
@sideangleside yupp, LGTM now.

2016-10-07 19:39 UTC, bergsjoh commented on bootstrap.py
> +      with open('/etc/yum/pluginconf.d/product-id.conf','w') as configfile:
6 months my friend, 6 months 👍

2016-10-08 07:11 UTC, evgeni commented on bootstrap.py
> +      with open('/etc/yum/pluginconf.d/product-id.conf','w') as configfile:
@bergsjoh partially true, production 3 is then over, but people will still have it...

2016-10-08 21:36 UTC, Rocco83 commented on bootstrap.py
> +      with open('/etc/yum/pluginconf.d/product-id.conf','w') as configfile:
Will have for a long time, i can ensure... 
I know that there are still RHEL4 and RHEL3 in prod.

2016-11-03 06:37 UTC, evgeni commented
merged in 7f84e1afe5cca26927aa2aafdcab3d5235c973d9

2016-11-03 06:37 UTC, closed without merging