remove Katello CA certs in clean_katello_agent
Katello/katello-client-bootstrap pull request #128
Opened 2016-11-14 23:53 UTC by sideangleside

In https://github.com/Katello/katello-client-bootstrap/pull/120, we added support for gracefully failing in the event that a system was already registered. (Done via checking for the presence of `/etc/rhsm/ca/katello-server-ca.pem` As newer versions of the katello-ca-consumer RPM no longer deploy `/etc/rhsm/ca/katello-server-ca.pem` directly, but call `katello-rhsm-consumer`, which deploys the file, the **clean_katello_agent** function needs to delete *both* the `/etc/rhsm/ca/katello-server-ca.pem` file AND the RPM.

2016-11-15 22:21 UTC, evgeni requested changes
https://docs.python.org/2/library/os.html#os.unlink

2016-11-15 23:22 UTC, sideangleside commented
Should we also remove the `rm -rf` in the `clean_puppet()` function? I considered going with a pure python approach, but used `rm` here to be consistent. I am fine with either approach.

2016-11-16 19:16 UTC, evgeni commented
Yeah, we probably should go all Python here. But in the puppet case we will need https://docs.python.org/2/library/shutil.html#shutil.rmtree

2016-11-17 11:18 UTC, sideangleside commented
Added two new helper functions,` delete_file()` & `delete_directory()` to support file and directory deletion and retrofitted our current file and directory deletions to use them. 

I suspect that as bootstrap evolves, we will need to delete additional files and directories, so it would be helpful to have proper functions, with our custom notification messages and the like.

2016-11-17 13:51 UTC, merged