Options for PE and RHEL-H added
Katello/katello-client-bootstrap pull request #130
Opened 2016-11-16 04:36 UTC by chopskxw

Options were added to configure systems to use puppet enterprise (v3) instead of integrated puppet in katello.  Additional mods may need to be made to be v4 compliant.  

Option added to configure virt-who on RHEL based systems that are configured as RHV/oVirt hypervisors.

2016-11-17 22:27 UTC, evgeni commented
Ohai,

I will add some inline comments, but here are a few general ones :-)

* can you sqash the changes in a few logical commits please?
* I don't think doing virt-who is bootstrap.py's job, we have Puppet/Ansible for that (but @sideangleside and @mccun934 might think otherwise)

2016-11-17 22:37 UTC, evgeni requested changes

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +def enable_satellite_tools():
that's a downstream Satellite thing, now replaced with `--enablerepos` upstream.

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +    exec_failexit("subscription-manager attach --pool=$(subscription-manager list --available --matches='Puppet Enterprise' --pool-only)" )
the pool belongs into the activation-key, not into our calls

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +    exec_failexit("subscription-manager repos --enable=%s_Puppet_Enterprise_$(uname -r | cut -d. -f6)-pe-$(uname -r | cut -d. -f7)" % ( org_label ))
those two should be done using `--enablerepos` as we don't know how the repos will be called at the users setup

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +    exec_failexit("/usr/local/bin/puppet agent -t --server %s || true" % (options.pe_server_fqdn))
why `|| true`? this hides errors in puppet comms

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> -
pep8 wants this :)

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +def install_virt_who():
as mentioned, I don't think this belongs here

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +    enable_satellite_tools()
Satellite stuff…

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +    if os.path.isfile('/etc/yum.repos.d/pe_repo.repo'):
I *think* I'd leave that to the user. The file might be called differently too.

2016-11-17 22:37 UTC, evgeni commented on bootstrap.py
> +def install_pe_agent(org_name):
can't we merge that and install_puppet? just having a flag whether it's puppet or PE that is going to be installed?

2016-11-17 22:37 UTC, evgeni commented
Ah, and one more thing, we're missing a cleanup for PE installs.

2016-11-18 20:58 UTC, sideangleside commented on bootstrap.py
> +    exec_failexit("subscription-manager attach --pool=$(subscription-manager list --available --matches='Puppet Enterprise' --pool-only)" )
+1 Attaching subs is the activation keys' job. Also, this  assumes the custom Product is named **Puppet Enterprise** . 

Also, file operations (creates, deletes, moves & removes) should use native Python modules to remain consistent.

2016-11-18 20:59 UTC, sideangleside commented on bootstrap.py
> +    exec_failexit("subscription-manager repos --enable=%s_Puppet_Enterprise_$(uname -r | cut -d. -f6)-pe-$(uname -r | cut -d. -f7)" % ( org_label ))
Or done via the activation key. It is the user's choice, but -1 to hardcoded repo names.

2016-11-18 21:08 UTC, sideangleside commented
I don't think a function to install (and configure) virt-who is within the scope of what bootstrap is designed to do. I would be open to, as a courtesy to users who are using Katello solely as a content source and have no config mgmt, a generic function to install additional packages (provided in a comma separated fashion). After that, we are well into Puppet/Ansible territory.

2016-11-18 21:22 UTC, sideangleside commented on bootstrap.py
> +def install_pe_agent(org_name):
Yes. Though the PE Agent requires a bit more configuration especially if a user is using Trusted Facts.

2017-05-09 15:11 UTC, closed without merging