Update docs with more examples and updated help
Katello/katello-client-bootstrap pull request #163
Opened 2017-02-21 09:27 UTC by sideangleside

Updated README.md to include many more examples.

2017-02-22 09:46 UTC, sideangleside commented
Bah. Don't merge this PR. I forgot we have `EXAMPLES.md` with additional examples

2017-02-23 14:56 UTC, evgeni commented
Can you check that "Puppet" is always spelled "Puppet", not "puppet" in the text parts, and "Foreman" and "bootstrap.py" (not "Bootstrap.py"?)

2017-02-23 14:56 UTC, evgeni requested changes

2017-02-23 14:56 UTC, evgeni commented on README.md
> +* Running rhn-migrate-classic-to-rhsm (with the user provisioned activation key) to get product certs on a system
I think this should have been "provided"?

2017-02-23 14:56 UTC, evgeni commented on README.md
> +    --skip-puppet
`--skip puppet`, please :)

2017-02-23 14:56 UTC, evgeni commented on README.md
> +    --skip-foreman
`--skip foreman`, please :)

2017-02-23 14:56 UTC, evgeni commented on README.md
> +    --enablerepos=rhel-7-server-extras-rpms, rhel-7-server-optional-rpms
Dat space will break it!

2017-02-23 14:57 UTC, evgeni commented on README.md
> +### Registering a system to Foreman
Why Foreman and not "Foreman + Katello" as before? (just cuerious)

2017-02-23 15:03 UTC, sideangleside commented on README.md
> +* Running rhn-migrate-classic-to-rhsm (with the user provisioned activation key) to get product certs on a system
Yes. Damn autocorrect.

2017-02-23 15:04 UTC, sideangleside commented on README.md
> +    --skip-puppet
I didn't want to retroactively remove the old examples. They are still honored, so I'd rather have them documented. (Cause users will ask).

2017-02-23 15:04 UTC, sideangleside commented on README.md
> +    --skip-foreman
I didn't want to retroactively remove the old examples. They are still honored, so I'd rather have them documented. (Cause users will ask).

2017-02-23 15:26 UTC, sideangleside commented on README.md
> +### Registering a system to Foreman
inconsistent behavior is inconsistent

2017-02-23 17:28 UTC, evgeni approved these changes

2017-02-23 17:28 UTC, merged