Allow the user to provide an arbitrary hostname, overridding what is detected via socket.fqdn
Katello/katello-client-bootstrap pull request #164
Opened 2017-02-22 01:43 UTC by sideangleside

Many users have either hostnames that are short (`hostname -f` or python's `socket.getfqdn` returns a hostname that isn't an FQDN) or non-RFC compliant (containing a character such as an underscrore `-` which fails Foreman's hostname validation. 

However, due to $REASONS, the user cannot update his/her system. This PR adds a new option `--override-fqdn` which allows the user to specify the FQDN that willl be reported to Foreman

**Prereqs** 

The user needs to set to **False** the `create_new_host_when_facts_are_uploaded` and ` create_new_host_when_reports_are_uploaded` options. This can be done with hammer. 

~~~
hammer settings set --name  create_new_host_when_facts_are_uploaded --value false
hammer settings set --name  create_new_host_when_reports_are_uploaded --value false
~~~

2017-02-22 09:59 UTC, evgeni requested changes

2017-02-22 09:59 UTC, evgeni commented on bootstrap.py
> +        generate_katello_facts()
The call to `generate_katello_facts` in `install_prepreqs` can be removed then?

2017-02-22 09:59 UTC, evgeni commented on bootstrap.py
> +    """Write katello_facts file based on FQDN"""
Maybe add "should be run *after* katello-ca-consumer RPM was installed to override the generated facts there"?

2017-02-22 09:59 UTC, evgeni commented on bootstrap.py
> +    katellofacts.write('{"network.hostname-override":"%s"}\n' % (FQDN))
What is the difference?

2017-02-22 09:59 UTC, evgeni commented on bootstrap.py
> +    FQDN = socket.getfqdn()
I think `--override-fqdn` should have `default=socket.getfqdn()` and the both codepaths should be merged to one?

2017-02-22 09:59 UTC, evgeni commented on bootstrap.py
> +        HOSTNAME = options.override_fqdn
Missing a `.split('.')[0]`?

2017-02-22 09:59 UTC, evgeni commented on bootstrap.py
> +        DOMAIN = FQDN[FQDN.index('.') + 1:]
this will crash if the user passed a non-fqdn to --override-fqdn (and they will)

2017-02-22 16:14 UTC, sideangleside commented on bootstrap.py
> +    katellofacts.write('{"network.hostname-override":"%s"}\n' % (FQDN))
From @jlsherrill: "katello will prefer using network.fqdn,  network.hostname-override, and finally (if none of those are present) network.hostname" I changed our to using network.hostname-override from network.hostname (which we used previously) to be consistent with the katello-ca-consumer RPM.

2017-02-22 16:15 UTC, sideangleside commented on bootstrap.py
> +        generate_katello_facts()
Correct.  	b3fb7f8 removes it.

2017-02-22 16:16 UTC, sideangleside commented on bootstrap.py
> +    """Write katello_facts file based on FQDN"""
Ack.  added in d68157d

2017-02-22 16:16 UTC, sideangleside commented on bootstrap.py
> +        HOSTNAME = options.override_fqdn
This is obsoleted by the refactoring in 15020bf

2017-02-22 16:16 UTC, sideangleside commented on bootstrap.py
> +    FQDN = socket.getfqdn()
This is obsoleted by the refactoring in 15020bf

2017-02-22 16:21 UTC, sideangleside commented
Thanks for the review @evgeni. 

In refactoring the code, I decided to rename `--override-fqdn` to `--fqdn`

2017-02-22 17:46 UTC, evgeni commented on bootstrap.py
> +    parser.add_option("--fqdn", dest="fqdn", help="Set an explicit FQDN, overriding detected FQDN from socket.getfqdn()", metavar="OVERRIDE_FQDN", default=socket.getfqdn())
how about adding `%default` to the help string, thus allowing the user to know what `socket.getfqdn()` detected beforehand? (see https://docs.python.org/2/library/optparse.html#generating-help)

2017-02-22 17:46 UTC, evgeni commented on bootstrap.py
> +    parser.add_option("--fqdn", dest="fqdn", help="Set an explicit FQDN, overriding detected FQDN from socket.getfqdn()", metavar="OVERRIDE_FQDN", default=socket.getfqdn())
I think the metavar should also be renamed to `FQDN` now, no?

2017-02-22 17:47 UTC, evgeni commented
Besides the two small comments about the param, LGTM. Did not run the code though.

2017-02-23 07:06 UTC, evgeni commented on bootstrap.py
> +    parser.add_option("--fqdn", dest="fqdn", help="Set an explicit FQDN, overriding detected FQDN from socket.getfqdn(), currently detected as %s" % socket.getfqdn(), metavar="FQDN", default=socket.g
The `default` value is stored as `%default`, no need to call `getfqdn()` again.

```python
parser.add_option("--fqdn", dest="fqdn", help="Set an explicit FQDN, overriding detected FQDN from socket.getfqdn(), currently detected as %default", metavar="FQDN", default=socket.getfqdn())```

2017-02-23 11:15 UTC, evgeni commented on bootstrap.py
> +    parser.add_option("--fqdn", dest="fqdn", help="Set an explicit FQDN, overriding detected FQDN from socket.getfqdn(), currently detected as %default", metavar="FQDN", default=socket.getfqdn())
I think this should not be bewteen `--legacy-login` and `--legacy-password` but before?

2017-02-23 11:16 UTC, evgeni commented
Needs trivial rebase against master.
Andy maybe add what you have in the "pre-reqs" above to the README? Oh and update the readme to have the newest switches :)

2017-02-23 13:47 UTC, merged